package main

import (
	"fmt"
	"mapreduce"
	"os"
	"sort"
	"strings"
	"unicode"
)

// The mapping function is called once for each piece of the input.
// In this framework, the key is the name of the file that is being processed,
// and the value is the file's contents. The return value should be a slice of
// key/value pairs, each represented by a mapreduce.KeyValue.
func mapF(document string, value string) (res []mapreduce.KeyValue) {
	// map: files → (word, documentName)

	words := strings.FieldsFunc(value, func(r rune) bool {
		return !unicode.IsLetter(r)
	})

	// initializing output
	pairs := make([]mapreduce.KeyValue, 0, len(words))

	// STEP2: create a mapreduce.KeyValue for each word
	alreadyread := make(map[string]bool)
	// we want a (word, documentName) to appear once even if the word is repeated in that same doc
	for _, word := range words {
		if !alreadyread[word] {
			pairs = append(pairs, mapreduce.KeyValue{Key: word, Value: document})
			alreadyread[word] = true
		}
	}
	return pairs

}

// The reduce function is called once for each key generated by Map, with a
// list of that key's string value (merged across all inputs). The return value
// should be a single output value for that key.
func reduceF(key string, values []string) string {
	//reduce: (word, documentName) → (#documents documents,sorted,and,separated,by,commas)

	docs := make([]string, 0, len(values))

	// STEP1: for each document that contains our key word
	for _, val := range values {
		// go through the docs sort
		// i already made sure there were no duplicates in map, but i dont think i should rely on that but oh well lol
		docs = append(docs, val)
	}

	sort.Strings(docs)
	count := len(docs)

	// converting total count back to str
	return fmt.Sprintf("%d %s", count, strings.Join(docs, ","))
}

// Can be run in 3 ways:
// 1) Sequential (e.g., go run wc.go master sequential x1.txt .. xN.txt)
// 2) Master (e.g., go run wc.go master localhost:7777 x1.txt .. xN.txt)
// 3) Worker (e.g., go run wc.go worker localhost:7777 localhost:7778 &)
func main() {
	if len(os.Args) < 4 {
		fmt.Printf("%s: see usage comments in file\n", os.Args[0])
	} else if os.Args[1] == "master" {
		var mr *mapreduce.Master
		if os.Args[2] == "sequential" {
			mr = mapreduce.Sequential("iiseq", os.Args[3:], 3, mapF, reduceF)
		} else {
			mr = mapreduce.Distributed("iiseq", os.Args[3:], 3, os.Args[2])
		}
		mr.Wait()
	} else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], mapF, reduceF, 100)
	}
}
