package main

import (
	"fmt"
	"mapreduce"
	"os"
	"strconv"
	"strings"
	"unicode"
)

// The mapping function is called once for each piece of the input.
// In this framework, the key is the name of the file that is being processed,
// and the value is the file's contents. The return value should be a slice of
// key/value pairs, each represented by a mapreduce.KeyValue.
func mapF(document string, value string) (res []mapreduce.KeyValue) {

	//example:  mapF("Hi.txt", "Hello, world! Hello Go.")
	// returns [
	//   {Key: "Hello", Value: "1"},
	//   {Key: "world", Value: "1"},
	//   {Key: "Hello", Value: "1"},
	//   {Key: "Go",    Value: "1"},
	// ]

	// STEP1: read every word in the document and process it
	// instead of splitting by space, im splitting by letters

	//FieldsFunc splits by accumalating all characters until the func given is true
	// so when i use !unicode.IsLetter im telling it to keep going until it encounters
	// a character that is not a letter and split there.
	words := strings.FieldsFunc(value, func(r rune) bool {
		return !unicode.IsLetter(r)
	})

	// initializing output
	pairs := make([]mapreduce.KeyValue, 0, len(words))

	// STEP2: create a mapreduce.KeyValue for each word
	for _, word := range words {
		pairs = append(pairs, mapreduce.KeyValue{Key: word, Value: "1"})
	}
	return pairs

}

// The reduce function is called once for each key generated by Map, with a
// list of that key's string value (merged across all inputs). The return value
// should be a single output value for that key.
func reduceF(key string, values []string) string {

	// example: reduceF("Hello", ["1","1"])
	// returns "2"

	count := 0

	// STEP1: for each occurence of a word in values,
	for _, val := range values {
		// theyre "1" so i need to convert to int
		valint, err := strconv.Atoi(val)
		if err != nil {
			fmt.Printf("[REDUCEF] error converting str to int")
		}

		// count the word
		count += valint
	}

	// converting total count back to str
	return strconv.Itoa(count)
}

// Can be run in 3 ways:
// 1) Sequential (e.g., go run wc.go master sequential x1.txt .. xN.txt)
// 2) Master (e.g., go run wc.go master localhost:7777 x1.txt .. xN.txt)
// 3) Worker (e.g., go run wc.go worker localhost:7777 localhost:7778 &)
func main() {
	if len(os.Args) < 4 {
		fmt.Printf("%s: see usage comments in file\n", os.Args[0])
	} else if os.Args[1] == "master" {
		var mr *mapreduce.Master
		if os.Args[2] == "sequential" {
			mr = mapreduce.Sequential("wcseq", os.Args[3:], 3, mapF, reduceF)
		} else {
			mr = mapreduce.Distributed("wcseq", os.Args[3:], 3, os.Args[2])
		}
		mr.Wait()
	} else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], mapF, reduceF, 100)
	}
}
